name: CI - Testes Unitários

on:
  pull_request:
    branches: ["main"]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Rodar testes
        run: npx jest